### PR TITLE
Adding documentation for lsp, documentation

### PR DESCRIPTION
**Pull request by lovestaco**
## What type of MR is this? 

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Doc Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] ⏩ Revert

## Description

Adding documentation for [LSP release](https://github.com/HexmosTech/Lama2/releases/tag/v1.5.8)

## Important files to start review from
* Ide/Editor support
* Contribute to LSP

## If documentation update is there then run `make mkdocs` once PR is in acceptable state.

- [x] 📓 make mkdocs
- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by shrsv** [comment]
Overall TOC, I think we have two main sections now:

1. Programmatic ally Executing an l2 file 
2. LSP Language services for L2 extension

You can have the other sections categorised properly under these two.

**Comment by shrsv** [comment]
> Launch the server using the following command:

We want to highlight our experience in how this works.

1. Usually you need a separate process to keep it running
2. One interacts using stdin/stdout with this server (link MS docs for support)
3. Link to our extension code relevant to starting the server

**Comment by shrsv** [comment]
```
The LSP server offers a custom method, `suggest/environmentVariables``, which provides autocompletion suggestions for environment variables. 
```

The symbol highlighting using backticks is messed up.

**Comment by shrsv** [comment]
Along with Goto Example (user level help), link relevant section of the VSCode extension.

**Comment by lovestaco** [comment]
> Along with Goto Example (user level help), link relevant section of the VSCode extension.

Will add after merging

**Comment by lovestaco** [comment]
> > Launch the server using the following command:
> 
> We want to highlight our experience in how this works.
> 
> 1. Usually you need a separate process to keep it running
> 2. One interacts using stdin/stdout with this server (link MS docs for support)
> 3. Link to our extension code relevant to starting the server

Will add the link to FE after merging 
`check out this section of our codebase.`

**Pull request merged**
